run:
  deadline: 5m
  skip-files:
  - "zz_generated.*\\.go$"
linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - gofmt
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - structcheck
    - unconvert
    - varcheck
  # Run with --fast=false for more extensive checks
  fast: true
  include:
  - EXC0002 # include "missing comments" issues from golint
  max-issues-per-linter: 0
  max-same-issues: 0