#############      builder                                  #############
FROM golang:1.22.5 AS builder

WORKDIR /go/src/github.com/falcosecurity/falcosidekick
COPY . .

RUN make falcosidekick

#############      base                                     #############
# FROM gcr.io/distroless/static-debian12:nonroot as base
FROM debian:latest as base
FROM base AS falcosidekick-fork

WORKDIR /

COPY --from=builder /go/src/github.com/falcosecurity/falcosidekick/falcosidekick /falcosidekick
ENTRYPOINT ["/falcosidekick"]

