name: tests

on:
  push:
    branches:
      - master
  pull_request:

permissions: {}

jobs:
  unit-tests:
    name: Run unit tests

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.25'
          cache: false
          check-latest: true

      - name: Run Go tests
        run: make test
